all: Evaluation_Script moses-scripts

Evaluation_Script:
	wget -qO - https://www.dropbox.com/s/5jw5maariwey080/Evaluation_Script.tar.gz | tar zxf -
moses-scripts:
	git clone https://github.com/marian-nmt/moses-scripts
